import Sidebar from '@/components/Sidebar'
import './globals.css'
import Header from '@/components/Header'

export const metadata = {
  title: 'Amazon Web Scrapper',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex bg-[#F7FBFF] h-screen'>
        <Sidebar/>
        <main className='py-10 md:px-10 px-1 w-full mx-auto overflow-y-auto scrollbar-thin scrollbar-thumb-sky-600 scrollbar-track-sky-100'>
          <Header/>
          {children}
        </main>
      </body>
    </html>
  )
}
